version: '3.8'

services:
  rekov-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
    restart: unless-stopped
    networks:
      - rekov_net

networks:
  rekov_net:
    driver: bridge
