'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'EN' | 'HI' | 'BN' | 'SAT' | 'KVN' | 'HOC' | 'UNW' | 'TA' | 'TE' | 'MR' | 'GU' | 'UR' | 'KN' | 'ML' | 'PA' | 'ES' | 'FR' | 'DE' | 'ZH' | 'AR' | 'RU' | 'JA';

const TRANSLATIONS: Record<Language, Record<string, string>> = {
  EN: {
    check_in: 'CHECK-IN',
    manual_entry: 'Manual Entry',
    status_check: 'STATUS CHECK',
    token_lookup: 'Token Lookup',
    schedules: 'SCHEDULES',
    doctor_timings: 'Doctor Timings',
    listening: 'Listening... Tap to stop.',
    processing: 'Processing',
    understood: 'Understood',
    network_error: 'Network Error. Please try again.',
    welcome: 'Welcome to MediVERSE',
    hospital_system: 'Hospital Self-Service System',
    select_language: 'SELECT LANGUAGE',
    choose_pref: 'Choose your preferred language to continue.',
    continue_btn: 'CONTINUE',
    gesture_on: 'Gesture Control ON (No Screen Touch)',
    gesture_off: 'Enable Gestures (No Screen Touch Method)',
    how_to_use: 'HOW TO USE',
    step_1: 'Step 1: Face the camera -- your face must be visible.',
    step_2: 'Step 2: Raise one finger = Pointer moves on screen.',
    step_3: 'Step 3: Pinch (thumb + index) = Click.',
    face_req: 'Face detection required for security.',
    no_touch: 'No screen touch needed.',
    gesture_desc: 'Gesture mode uses your camera. No data is stored.',
    primary_lang: 'PRIMARY',
    jharkhand_lang: 'JHARKHAND REGIONAL',
    other_indian: 'OTHER INDIAN',
    foreign_lang: 'FOREIGN',
    voice_assist: 'VOICE ASSIST',
    speak_naturally: 'Speak Naturally',
    qr_check_in: 'QR CHECK-IN',
    scan_whatsapp: 'Scan with WhatsApp',
  },
  HI: {
    check_in: 'चेक-इन',
    manual_entry: 'मैन्युअल प्रविष्टि',
    status_check: 'स्थिति जांचें',
    token_lookup: 'टोकन खोजें',
    schedules: 'समय सारिणी',
    doctor_timings: 'डॉक्टर का समय',
    listening: 'सुन रहा हूँ... रोकने के लिए टैप करें।',
    processing: 'प्रोसेसिंग',
    understood: 'समझ गया',
    network_error: 'नेटवर्क त्रुटि। कृपया पुनः प्रयास करें।',
    welcome: 'MediVERSE में आपका स्वागत है',
    hospital_system: 'अस्पताल स्वयं-सेवा प्रणाली',
    select_language: 'भाषा चुनें',
    choose_pref: 'जारी रखने के लिए अपनी पसंदीदा भाषा चुनें।',
    continue_btn: 'आगे बढ़ें',
    gesture_on: 'इशारे चालू हैं (बिना छुए)',
    gesture_off: 'इशारे चालू करें (स्क्रीन छूने की ज़रूरत नहीं)',
    how_to_use: 'कैसे इस्तेमाल करें',
    step_1: 'पहला कदम: कैमरे के सामने आएं -- चेहरा दिखना ज़रूरी है।',
    step_2: 'दूसरा कदम: एक उंगली उठाएं = स्क्रीन पर पॉइंटर चलेगा।',
    step_3: 'तीसरा कदम: चुटकी (अंगूठा + उंगली) = क्लिक।',
    face_req: 'सुरक्षा के लिए चेहरे की पहचान जरूरी है।',
    no_touch: 'स्क्रीन छूने की ज़रूरत नहीं।',
    gesture_desc: 'इशारे मोड आपके कैमरे का उपयोग करता है। कोई डेटा सेव नहीं होता।',
    primary_lang: 'मुख्य भाषाएं',
    jharkhand_lang: 'झारखण्ड की भाषाएं',
    other_indian: 'अन्य भारतीय भाषाएं',
    foreign_lang: 'विदेशी भाषाएं',
    voice_assist: 'आवाज़ सहायक',
    speak_naturally: 'स्वाभाविक रूप से बोलें',
    qr_check_in: 'QR चेक-इन',
    scan_whatsapp: 'WhatsApp से स्कैन करें',
  },
  BN: {
    check_in: 'চেক-ইন',
    manual_entry: 'ম্যানুয়াল এন্ট্রি',
    status_check: 'স্ট্যাটাস চেক',
    token_lookup: 'টোকেন খুঁজুন',
    schedules: 'সময়সূচী',
    doctor_timings: 'ডাক্তারের সময়',
    listening: 'শুনছি... থামাতে ট্যাপ করুন।',
    processing: 'প্রসেসিং',
    understood: 'বুঝেছি',
    network_error: 'নেটওয়ার্ক ত্রুটি। আবার চেষ্টা করুন।',
    welcome: 'MediVERSE-এ স্বাগতম',
    hospital_system: 'হাসপাতাল স্ব-সেবা সিস্টেম',
    select_language: 'ভাষা নির্বাচন করুন',
    choose_pref: 'চালিয়ে যেতে আপনার পছন্দের ভাষা চয়ন করুন।',
    continue_btn: 'চালিয়ে যান',
    gesture_on: 'অঙ্গভঙ্গি চালু (স্ক্রিন স্পর্শ ছাড়া)',
    gesture_off: 'অঙ্গভঙ্গি সক্ষম করুন (স্ক্রিন স্পর্শ ছাড়া)',
    how_to_use: 'কীভাবে ব্যবহার করবেন',
    step_1: 'ধাপ ১: ক্যামেরার দিকে তাকান -- আপনার মুখ দেখা যেতে হবে।',
    step_2: 'ধাপ ২: এক আঙুল তুলুন = পয়েন্টার নড়বে।',
    step_3: 'ধাপ ৩: চিমটি কাটুন (আঙুল + বুড়ো আঙুল) = ক্লিক করুন।',
    face_req: 'নিরাপত্তার জন্য মুখ সনাক্তকরণ প্রয়োজন।',
    no_touch: 'স্ক্রিন স্পর্শের প্রয়োজন নেই।',
    gesture_desc: 'জেসচার মোড ক্যামেরা ব্যবহার করে। কোনো ডেটা সেভ হয় না।',
    primary_lang: 'প্রধান ভাষা',
    jharkhand_lang: 'ঝাড়খণ্ডের ভাষা',
    other_indian: 'অন্যান্য ভারতীয়',
    foreign_lang: 'বিদেশী',
  },
  SAT: {
    check_in: 'ᱪᱮᱠ-ᱤᱱ',
    manual_entry: 'ᱢᱮᱱᱩᱣᱟᱞ ᱮᱱᱴᱨᱤ',
    status_check: 'ᱥᱴᱮᱴᱟᱥ ᱪᱮᱠ',
    token_lookup: 'ᱴᱚᱠᱮᱱ ᱥᱮᱸᱫᱽᱨᱟ',
    schedules: 'ᱚᱠᱛᱚ ᱥᱟᱠᱟᱢ',
    doctor_timings: 'ᱰᱟᱠᱴᱚᱨ ᱚᱠᱛᱚ',
    listening: 'ᱟᱸᱡᱚᱢᱮᱫᱟ... ᱛᱤᱸᱜᱩ ᱞᱟᱹᱜᱤᱫ ᱴᱮᱯ ᱢᱮ᱾',
    processing: 'ᱯᱨᱚᱥᱮᱥᱤᱝ',
    understood: 'ᱵᱩᱡᱷᱟᱹᱣ ᱮᱱᱟ',
    network_error: 'ᱱᱮᱴᱣᱟᱨᱠ ᱮᱨᱚᱨ᱾ ᱫᱚᱦᱲᱟ ᱪᱮᱥᱴᱟ ᱢᱮ᱾',
    welcome: 'MediVERSE ᱨᱮ ᱥᱟᱹᱜᱩᱱ ᱫᱟᱨᱟᱢ',
    hospital_system: 'ᱦᱟᱥᱯᱟᱛᱟᱞ ᱥᱮᱞᱯᱷ-ᱥᱟᱨᱵᱷᱤᱥ ᱥᱤᱥᱴᱟᱢ',
    select_language: 'ᱯᱟᱹᱨᱥᱤ ᱵᱟᱪᱷᱟᱣ ᱢᱮ',
    choose_pref: 'ᱢᱟᱲᱟᱝ ᱥᱮᱱᱚᱜ ᱞᱟᱹᱜᱤᱫ ᱟᱢᱟᱜ ᱯᱟᱹᱨᱥᱤ ᱵᱟᱪᱷᱟᱣ ᱢᱮ᱾',
    continue_btn: 'ᱢᱟᱲᱟᱝ ᱥᱮᱱᱚᱜ',
    gesture_on: 'ᱤᱥᱟᱨᱟ ᱪᱟᱹᱞᱩ ᱢᱮᱱᱟᱜ-ᱟ (ᱵᱤᱱᱟᱹ ᱡᱚᱴᱮᱫ)',
    gesture_off: 'ᱤᱥᱟᱨᱟ ᱪᱟᱹᱞᱩᱭ ᱢᱮ',
    how_to_use: 'ᱪᱮᱫ ᱞᱮᱠᱟ ᱵᱮᱵᱷᱟᱨᱟ',
    step_1: 'ᱫᱷᱟᱯ ᱑: ᱠᱮᱢᱮᱨᱟ ᱥᱟᱢᱟᱝ ᱨᱮ ᱦᱤᱡᱩᱜ ᱢᱮ -- ᱢᱮᱫᱦᱟᱸ ᱧᱮᱞᱚᱜ ᱞᱟᱹᱠᱛᱤ᱾',
    step_2: 'ᱫᱷᱟᱯ ᱒: ᱢᱤᱫᱴᱟᱹᱝ ᱠᱟᱹᱴᱩᱵ ᱨᱟᱠᱟᱵ ᱢᱮ = ᱯᱚᱭᱮᱱᱴᱟᱨ ᱞᱟᱲᱟᱜ-ᱟ᱾',
    step_3: 'ᱫᱷᱟᱯ ３: ᱪᱤᱯᱩᱫ (ᱮᱸᱜᱟ + ᱩᱫᱩᱜ ᱠᱟᱹᱴᱩᱵ) = ᱠᱞᱤᱠ᱾',
    face_req: 'ᱨᱩᱠᱷᱤᱭᱟᱹ ᱞᱟᱹᱜᱤᱫ ᱢᱮᱫᱦᱟᱸ ᱧᱮᱞ ᱞᱟᱹᱠᱛᱤ᱾',
    no_touch: 'ᱥᱠᱨᱤᱱ ᱡᱚᱴᱮᱫ ᱵᱟᱝ ᱞᱟᱹᱠᱛᱤ᱾',
    gesture_desc: 'ᱤᱥᱟᱨᱟ ᱢᱳᱰ ᱟᱢᱟᱜ ᱠᱮᱢᱮᱨᱟ ᱵᱮᱵᱷᱟᱨᱟ᱾ ᱰᱮᱴᱟ ᱵᱟᱝ ᱫᱚᱦᱚᱜ-ᱟ᱾',
    primary_lang: 'ᱢᱩᱬᱩᱛ',
    jharkhand_lang: 'ᱡᱷᱟᱨᱠᱷᱚᱸᱰ ᱨᱮᱱᱟᱜ',
    other_indian: 'ᱮᱴᱟᱜ ᱥᱤᱧᱚᱛᱤᱭᱟᱹ',
    foreign_lang: 'ᱵᱤᱫᱮᱥᱤ',
  },
  KVN: {
    check_in: 'चेक-इन',
    manual_entry: 'मैन्युअल प्रविष्टि',
    status_check: 'स्थिति जांचें',
    token_lookup: 'टोकन खोजें',
    schedules: 'समय सारिणी',
    doctor_timings: 'डॉक्टर का समय',
    listening: 'सुन रहा हूँ... रोकने के लिए टैप करें।',
    processing: 'प्रोसेसिंग',
    understood: 'समझ गया',
    network_error: 'नेटवर्क त्रुटि। कृपया पुनः प्रयास करें।',
    welcome: 'MediVERSE में आपका स्वागत है',
    hospital_system: 'अस्पताल स्वयं-सेवा प्रणाली',
    select_language: 'भाषा चुनें',
    choose_pref: 'जारी रखने के लिए अपनी पसंदीदा भाषा चुनें।',
    continue_btn: 'आगे बढ़ें',
    gesture_on: 'इशारे चालू हैं (बिना छुए)',
    gesture_off: 'इशारे चालू करें (स्क्रीन छूने की ज़रूरत नहीं)',
    how_to_use: 'कैसे इस्तेमाल करें',
    step_1: 'पहला कदम: कैमरे के सामने आएं -- चेहरा दिखना ज़रूरी है।',
    step_2: 'दूसरा कदम: एक उंगली उठाएं = स्क्रीन पर पॉइंटर चलेगा।',
    step_3: 'तीसरा कदम: चुटकी (अंगूठा + उंगली) = क्लिक।',
    face_req: 'सुरक्षा के लिए चेहरे की पहचान जरूरी है।',
    no_touch: 'स्क्रीन छूने की ज़रूरत नहीं।',
    gesture_desc: 'इशारे मोड आपके कैमरे का उपयोग करता है। कोई डेटा सेव नहीं होता।',
    primary_lang: 'मुख्य भाषाएं',
    jharkhand_lang: 'झारखण्ड की भाषाएं',
    other_indian: 'अन्य भारतीय भाषाएं',
    foreign_lang: 'विदेशी भाषाएं',
  },
  HOC: {
    check_in: 'चेक-इन',
    manual_entry: 'मैन्युअल प्रविष्टि',
    status_check: 'स्थिति जांचें',
    token_lookup: 'टोकन खोजें',
    schedules: 'समय सारिणी',
    doctor_timings: 'डॉक्टर का समय',
    listening: 'सुन रहा हूँ... रोकने के लिए टैप करें।',
    processing: 'प्रोसेसिंग',
    understood: 'समझ गया',
    network_error: 'नेटवर्क त्रुटि। कृपया पुनः प्रयास करें।',
    welcome: 'MediVERSE में आपका स्वागत है',
    hospital_system: 'अस्पताल स्वयं-सेवा प्रणाली',
    select_language: 'भाषा चुनें',
    choose_pref: 'जारी रखने के लिए अपनी पसंदीदा भाषा चुनें।',
    continue_btn: 'आगे बढ़ें',
    gesture_on: 'इशारे चालू हैं (बिना छुए)',
    gesture_off: 'इशारे चालू करें (स्क्रीन छूने की ज़रूरत नहीं)',
    how_to_use: 'कैसे इस्तेमाल करें',
    step_1: 'पहला कदम: कैमरे के सामने आएं -- चेहरा दिखना ज़रूरी है।',
    step_2: 'दूसरा कदम: एक उंगली उठाएं = स्क्रीन पर पॉइंटर चलेगा।',
    step_3: 'तीसरा कदम: चुटकी (अंगूठा + उंगली) = क्लिक।',
    face_req: 'सुरक्षा के लिए चेहरे की पहचान जरूरी है।',
    no_touch: 'स्क्रीन छूने की ज़रूरत नहीं।',
    gesture_desc: 'इशारे मोड आपके कैमरे का उपयोग करता है। कोई डेटा सेव नहीं होता।',
    primary_lang: 'मुख्य भाषाएं',
    jharkhand_lang: 'झारखण्ड की भाषाएं',
    other_indian: 'अन्य भारतीय भाषाएं',
    foreign_lang: 'विदेशी भाषाएं',
  },
  UNW: {
    check_in: 'चेक-इन',
    manual_entry: 'मैन्युअल प्रविष्टि',
    status_check: 'स्थिति जांचें',
    token_lookup: 'टोकन खोजें',
    schedules: 'समय सारिणी',
    doctor_timings: 'डॉक्टर का समय',
    listening: 'सुन रहा हूँ... रोकने के लिए टैप करें।',
    processing: 'प्रोसेसिंग',
    understood: 'समझ गया',
    network_error: 'नेटवर्क त्रुटि। कृपया पुनः प्रयास करें।',
    welcome: 'MediVERSE में आपका स्वागत है',
    hospital_system: 'अस्पताल स्वयं-सेवा प्रणाली',
    select_language: 'भाषा चुनें',
    choose_pref: 'जारी रखने के लिए अपनी पसंदीदा भाषा चुनें।',
    continue_btn: 'आगे बढ़ें',
    gesture_on: 'इशारे चालू हैं (बिना छुए)',
    gesture_off: 'इशारे चालू करें (स्क्रीन छूने की ज़रूरत नहीं)',
    how_to_use: 'कैसे इस्तेमाल करें',
    step_1: 'पहला कदम: कैमरे के सामने आएं -- चेहरा दिखना ज़रूरी है।',
    step_2: 'दूसरा कदम: एक उंगली उठाएं = स्क्रीन पर पॉइंटर चलेगा।',
    step_3: 'तीसरा कदम: चुटकी (अंगूठा + उंगली) = क्लिक।',
    face_req: 'सुरक्षा के लिए चेहरे की पहचान जरूरी है।',
    no_touch: 'स्क्रीन छूने की ज़रूरत नहीं।',
    gesture_desc: 'इशारे मोड आपके कैमरे का उपयोग करता है। कोई डेटा सेव नहीं होता।',
    primary_lang: 'मुख्य भाषाएं',
    jharkhand_lang: 'झारखण्ड की भाषाएं',
    other_indian: 'अन्य भारतीय भाषाएं',
    foreign_lang: 'विदेशी भाषाएं',
  },
  TA: {
    check_in: 'செக்-இன்',
    manual_entry: 'கைமுறை உள்ளீடு',
    status_check: 'நிலை சரிபார்ப்பு',
    token_lookup: 'டோக்கன் தேடல்',
    schedules: 'அட்டவணைகள்',
    doctor_timings: 'மருத்துவர் நேரங்கள்',
    listening: 'கேட்கிறது... நிறுத்த தட்டவும்.',
    processing: 'செயலாக்கப் படுகிறது',
    understood: 'புரிந்தது',
    network_error: 'நெட்வொர்க் பிழை. மீண்டும் முயற்சிக்கவும்.',
    welcome: 'MediVERSEக்கு வரவேற்கிறோம்',
    hospital_system: 'மருத்துவமனை சுய சேவை அமைப்பு',
    select_language: 'மொழியைத் தேர்ந்தெடுக்கவும்',
    choose_pref: 'தொடர உங்கள் விருப்ப மொழியைத் தேர்ந்தெடுக்கவும்.',
    continue_btn: 'தொடர்க',
    gesture_on: 'சைகை கட்டுப்பாடு ஆன் (திரை தொடுதல் இல்லை)',
    gesture_off: 'சைகைகளை இயக்கு',
    how_to_use: 'எப்படி பயன்படுத்துவது',
    step_1: 'படி 1: கேமராவை எதிர்கொள்ளுங்கள் -- உங்கள் முகம் தெரிய வேண்டும்.',
    step_2: 'படி 2: ஒரு விரலை உயர்த்தவும் = திரையில் கர்சர் நகரும்.',
    step_3: 'படி 3: கிள்ளவும் (கட்டைவிரல் + ஆள்காட்டி விரல்) = கிளிக்.',
    face_req: 'பாதுகாப்பிற்காக முகம் கண்டறிதல் அவசியம்.',
    no_touch: 'திரையைத் தொட தேவையில்லை.',
    gesture_desc: 'சைகை பயன்முறை உங்கள் கேமராவைப் பயன்படுத்துகிறது. எந்த தரவும் சேமிக்கப்படாது.',
    primary_lang: 'முதன்மை',
    jharkhand_lang: 'ஜார்க்கண்ட் பிராந்தியம்',
    other_indian: 'மற்ற இந்திய மொழிகள்',
    foreign_lang: 'வெளிநாட்டு',
  },
  TE: {
    check_in: 'చెక్-ఇన్',
    manual_entry: 'మాన్యువల్ ఎంట్రీ',
    status_check: 'స్థితి తనిఖీ',
    token_lookup: 'టోకెన్ శోధన',
    schedules: 'షెడ్యూల్స్',
    doctor_timings: 'డాక్టర్ సమయాలు',
    listening: 'వింటున్నాము... ఆపడానికి నొక్కండి.',
    processing: 'ప్రాసెసింగ్',
    understood: 'అర్థమైంది',
    network_error: 'నెట్‌వర్క్ లోపం. మళ్లీ ప్రయత్నించండి.',
    welcome: 'MediVERSEకు స్వాగతం',
    hospital_system: 'ఆసుపత్రి స్వయం-సేవ వ్యవస్థ',
    select_language: 'భాషను ఎంచుకోండి',
    choose_pref: 'కొనసాగించడానికి మీకు ఇష్టమైన భాషను ఎంచుకోండి.',
    continue_btn: 'కొనసాగించు',
    gesture_on: 'సంజ్ఞ నియంత్రణ ఆన్ (స్క్రీన్ టచ్ లేదు)',
    gesture_off: 'సంజ్ఞలను ప్రారంభించు',
    how_to_use: 'ఎలా ఉపయోగించాలి',
    step_1: 'దశ 1: కెమెరా వైపు చూడండి -- మీ ముఖం కనిపించాలి.',
    step_2: 'దశ 2: ఒక వేలు పైకెత్తండి = స్క్రీన్‌పై పాయింటర్ కదులుతుంది.',
    step_3: 'దశ 3: గిల్లడం (బొటనవేలు + చూపుడు వేలు) = క్లిక్.',
    face_req: 'భద్రత కోసం ముఖ గుర్తింపు అవసరం.',
    no_touch: 'స్క్రీన్ టచ్ అవసరం లేదు.',
    gesture_desc: 'సంజ్ఞ మోడ్ మీ కెమెరాను ఉపయోగిస్తుంది. ఏ డేటా నిల్వ చేయబడదు.',
    primary_lang: 'ప్రధాన',
    jharkhand_lang: 'జార్ఖండ్ ప్రాంతీయం',
    other_indian: 'ఇతర భారతీయ',
    foreign_lang: 'విదేశీ',
  },
  MR: {
    check_in: 'चेक-इन',
    manual_entry: 'मॅन्युअल एंट्री',
    status_check: 'स्थिती तपासा',
    token_lookup: 'टोकन शोधा',
    schedules: 'वेळापत्रक',
    doctor_timings: 'डॉक्टरांची वेळ',
    listening: 'ऐकत आहे... थांबवण्यासाठी टॅप करा.',
    processing: 'प्रक्रिया करत आहे',
    understood: 'समजले',
    network_error: 'नेटवर्क त्रुटी. कृपया पुन्हा प्रयत्न करा.',
    welcome: 'MediVERSE मध्ये आपले स्वागत आहे',
    hospital_system: 'रुग्णालय स्व-सेवा प्रणाली',
    select_language: 'भाषा निवडा',
    choose_pref: 'पुढे जाण्यासाठी तुमची पसंतीची भाषा निवडा.',
    continue_btn: 'पुढे जा',
    gesture_on: 'हावभाव नियंत्रण चालू (स्क्रीन स्पर्श नाही)',
    gesture_off: 'हावभाव सक्षम करा',
    how_to_use: 'कसे वापरावे',
    step_1: 'पायरी १: कॅमेरा समोर पहा -- तुमचा चेहरा दिसला पाहिजे.',
    step_2: 'पायरी २: एक बोट वर करा = स्क्रीनवर पॉईंटर हलतो.',
    step_3: 'पायरी ३: चिमटी काढा (अंगठा + तर्जनी) = क्लिक करा.',
    face_req: 'सुरक्षेसाठी चेहरा ओळखणे आवश्यक आहे.',
    no_touch: 'स्क्रीनला स्पर्श करण्याची गरज नाही.',
    gesture_desc: 'हावभाव मोड आपला कॅमेरा वापरतो. कोणताही डेटा जतन केला जात नाही.',
    primary_lang: 'प्राथमिक',
    jharkhand_lang: 'झारखंड प्रादेशिक',
    other_indian: 'इतर भारतीय',
    foreign_lang: 'परदेशी',
    voice_assist: 'आवाज़ सहायक',
    speak_naturally: 'स्वाभाविक रूप से बोलें',
    qr_check_in: 'QR चेक-इन',
    scan_whatsapp: 'WhatsApp से स्कैन करें',
  },
  GU: {
    check_in: 'ચેક-ઇન',
    manual_entry: 'મેન્યુઅલ એન્ટ્રી',
    status_check: 'સ્થિતિ તપાસ',
    token_lookup: 'ટોકન શોધો',
    schedules: 'સમયપત્રક',
    doctor_timings: 'ડૉક્ટરનો સમય',
    listening: 'સાંભળી રહ્યા છીએ... રોકવા માટે ટેપ કરો.',
    processing: 'પ્રક્રિયા થઈ રહી છે',
    understood: 'સમજી ગયા',
    network_error: 'નેટવર્ક ભૂલ. કૃપા કરીને ફરી પ્રયાસ કરો.',
    welcome: 'MediVERSE માં આપનું સ્વાગત છે',
    hospital_system: 'હોસ્પિટલ સ્વ-સેવા સિસ્ટમ',
    select_language: 'ભાષા પસંદ કરો',
    choose_pref: 'ચાલુ રાખવા માટે તમારી પસંદગીની ભાષા પસંદ કરો.',
    continue_btn: 'ચાલુ રાખો',
    gesture_on: 'જેસ્ચર કંટ્રોલ ઓન (કોઈ સ્ક્રીન ટચ નહીં)',
    gesture_off: 'જેસ્ચર્સ સક્ષમ કરો',
    how_to_use: 'કેવી રીતે વાપરવું',
    step_1: 'પગલું ૧: કેમેરા સામે જુઓ -- તમારો ચહેરો દેખાવો જોઈએ.',
    step_2: 'પગલું ૨: એક આંગળી ઊંચી કરો = સ્ક્રીન પર પોઇન્ટર ખસે છે.',
    step_3: 'પગલું ૩: ચપટી ભરો (અંગૂઠો + તર્જની) = ક્લિક કરો.',
    face_req: 'સુરક્ષા માટે ચહેરો ઓળખવો જરૂરી છે.',
    no_touch: 'સ્ક્રીન ટચની જરૂર નથી.',
    gesture_desc: 'જેસ્ચર મોડ તમારા કેમેરાનો ઉપયોગ કરે છે. કોઈ ડેટા સાચવવામાં આવતો નથી.',
    primary_lang: 'પ્રાથમિક',
    jharkhand_lang: 'ઝારખંડ પ્રાદેશિક',
    other_indian: 'અન્ય ભારતીય',
    foreign_lang: 'વિદેશી',
  },
  UR: {
    check_in: 'چیک ان',
    manual_entry: 'دستی اندراج',
    status_check: 'حیثیت کی جانچ',
    token_lookup: 'ٹوکن تلاش کریں',
    schedules: 'اوقات',
    doctor_timings: 'ڈاکٹر کے اوقات',
    listening: 'سن رہا ہے... روکنے کے لئے تھپتھپائیں۔',
    processing: 'پروسیسنگ',
    understood: 'سمجھ گیا',
    network_error: 'نیٹ ورک کی خرابی۔ براہ کرم دوبارہ کوشش کریں۔',
    welcome: 'MediVERSE میں خوش آمدید',
    hospital_system: 'اسپتال سیلف سروس سسٹم',
    select_language: 'زبان منتخب کریں',
    choose_pref: 'جاری رکھنے کے لئے اپنی پسندیدہ زبان منتخب کریں۔',
    continue_btn: 'جاری رکھیں',
    gesture_on: 'جیسچر کنٹرول آن (اسکرین کو چھونے کے بغیر)',
    gesture_off: 'جیسچرز فعال کریں',
    how_to_use: 'استعمال کا طریقہ',
    step_1: 'مرحلہ 1: کیمرے کا سامنا کریں -- آپ کا چہرہ نظر آنا چاہیے۔',
    step_2: 'مرحلہ 2: ایک انگلی اٹھائیں = اسکرین پر پوائنٹر حرکت کرتا ہے۔',
    step_3: 'مرحلہ 3: چٹکی بجائیں (انگوٹھا + شہادت کی انگلی) = کلک کریں۔',
    face_req: 'سیکیورٹی کے لئے چہرے کی شناخت درکار ہے۔',
    no_touch: 'اسکرین کو چھونے کی ضرورت نہیں۔',
    gesture_desc: 'جیسچر موڈ آپ کا کیمرہ استعمال کرتا ہے۔ کوئی ڈیٹا محفوظ نہیں ہوتا۔',
    primary_lang: 'بنیادی',
    jharkhand_lang: 'جھارکھنڈ علاقائی',
    other_indian: 'دیگر ہندوستانی',
    foreign_lang: 'غیر ملکی',
  },
  KN: {
    check_in: 'ಚೆಕ್-ಇನ್',
    manual_entry: 'ಹಸ್ತಚಾಲಿತ ನಮೂದು',
    status_check: 'ಸ್ಥಿತಿ ಪರಿಶೀಲನೆ',
    token_lookup: 'ಟೋಕನ್ ಹುಡುಕಾಟ',
    schedules: 'ವೇಳಾಪಟ್ಟಿಗಳು',
    doctor_timings: 'ವೈದ್ಯರ ಸಮಯಗಳು',
    listening: 'ಆಲಿಸಲಾಗುತ್ತಿದೆ... ನಿಲ್ಲಿಸಲು ಟ್ಯಾಪ್ ಮಾಡಿ.',
    processing: 'ಸಂಸ್ಕರಿಸಲಾಗುತ್ತಿದೆ',
    understood: 'ಅರ್ಥವಾಗಿದೆ',
    network_error: 'ನೆಟ್‌ವರ್ಕ್ ದೋಷ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    welcome: 'MediVERSE ಗೆ ಸ್ವಾಗತ',
    hospital_system: 'ಆಸ್ಪತ್ರೆ ಸ್ವಯಂ ಸೇವಾ ವ್ಯವಸ್ಥೆ',
    select_language: 'ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    choose_pref: 'ಮುಂದುವರಿಯಲು ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆರಿಸಿ.',
    continue_btn: 'ಮುಂದುವರಿಸಿ',
    gesture_on: 'ಸನ್ನೆ ನಿಯಂತ್ರಣ ಆನ್ (ಸ್ಕ್ರೀನ್ ಸ್ಪರ್ಶವಿಲ್ಲ)',
    gesture_off: 'ಸನ್ನೆಗಳನ್ನು ಸಕ್ರಿಯಗೊಳಿಸಿ',
    how_to_use: 'ಬಳಸುವುದು ಹೇಗೆ',
    step_1: 'ಹಂತ 1: ಕ್ಯಾಮೆರಾವನ್ನು ಎದುರಿಸಿ -- ನಿಮ್ಮ ಮುಖ ಕಾಣಿಸಬೇಕು.',
    step_2: 'ಹಂತ 2: ಒಂದು ಬೆರಳನ್ನು ಮೇಲಕ್ಕೆತ್ತಿ = ಪರದೆಯ ಮೇಲೆ ಪಾಯಿಂಟರ್ ಚಲಿಸುತ್ತದೆ.',
    step_3: 'ಹಂತ 3: ಚಿವುಟಿ (ಹೆಬ್ಬೆರಳು + ತೋರುಬೆರಳು) = ಕ್ಲಿಕ್.',
    face_req: 'ಭದ್ರತೆಗಾಗಿ ಮುಖ ಗುರುತಿಸುವಿಕೆ ಅಗತ್ಯವಿದೆ.',
    no_touch: 'ಪರದೆಯನ್ನು ಸ್ಪರ್ಶಿಸುವ ಅಗತ್ಯವಿಲ್ಲ.',
    gesture_desc: 'ಸನ್ನೆ ಮೋಡ್ ನಿಮ್ಮ ಕ್ಯಾಮೆರಾವನ್ನು ಬಳಸುತ್ತದೆ. ಯಾವುದೇ ಡೇಟಾವನ್ನು ಉಳಿಸಲಾಗುವುದಿಲ್ಲ.',
    primary_lang: 'ಪ್ರಾಥಮಿಕ',
    jharkhand_lang: 'ಜಾರ್ಖಂಡ್ ಪ್ರಾದೇಶಿಕ',
    other_indian: 'ಇತರ ಭಾರತೀಯ',
    foreign_lang: 'ವಿದೇಶಿ',
  },
  ML: {
    check_in: 'ചെക്ക്-ഇൻ',
    manual_entry: 'മാനുവൽ എൻട്രി',
    status_check: 'സ്റ്റാറ്റസ് പരിശോധന',
    token_lookup: 'ടോക്കൺ തിരയൽ',
    schedules: 'ഷെഡ്യൂളുകൾ',
    doctor_timings: 'ഡോക്ടറുടെ സമയങ്ങൾ',
    listening: 'കേൾക്കുന്നു... നിർത്താൻ ടാപ്പ് ചെയ്യുക.',
    processing: 'പ്രോസസ്സ് ചെയ്യുന്നു',
    understood: 'മനസ്സിലായി',
    network_error: 'നെറ്റ്‌വർക്ക് പിശക്. വീണ്ടും ശ്രമിക്കുക.',
    welcome: 'MediVERSE-ലേക്ക് സ്വാഗതം',
    hospital_system: 'ആശുപത്രി സ്വയം സേവന സംവിധാനം',
    select_language: 'ഭാഷ തിരഞ്ഞെടുക്കുക',
    choose_pref: 'തുടരുന്നതിന് നിങ്ങളുടെ പ്രിയപ്പെട്ട ഭാഷ തിരഞ്ഞെടുക്കുക.',
    continue_btn: 'തുടരുക',
    gesture_on: 'ജെസ്ചർ കൺട്രോൾ ഓൺ (സ്ക്രീൻ ടച്ച് ഇല്ല)',
    gesture_off: 'ജെസ്ചറുകൾ പ്രവർത്തനക്ഷമമാക്കുക',
    how_to_use: 'എങ്ങനെ ഉപയോഗിക്കാം',
    step_1: 'ഘട്ടം 1: ക്യാമറയെ അഭിമുഖീകരിക്കുക -- നിങ്ങളുടെ മുഖം കാണണം.',
    step_2: 'ഘട്ടം 2: ഒരു വിരൽ ഉയർത്തുക = പോയിന്റർ സ്ക്രീനിൽ നീങ്ങുന്നു.',
    step_3: 'ഘട്ടം 3: പിഞ്ച് ചെയ്യുക (തള്ളവിരൽ + ചൂണ്ടുവിരൽ) = ക്ലിക്ക് ചെയ്യുക.',
    face_req: 'സുരക്ഷയ്ക്കായി മുഖം തിരിച്ചറിയൽ ആവശ്യമാണ്.',
    no_touch: 'സ്ക്രീൻ ടച്ച് ആവശ്യമില്ല.',
    gesture_desc: 'ജെസ്ചർ മോഡ് നിങ്ങളുടെ ക്യാമറ ഉപയോഗിക്കുന്നു. ഡാറ്റയൊന്നും സംരക്ഷിക്കില്ല.',
    primary_lang: 'പ്രൈമറി',
    jharkhand_lang: 'ജാർഖണ്ഡ് പ്രാദേശികം',
    other_indian: 'മറ്റ് ഇന്ത്യൻ',
    foreign_lang: 'വിദേശ',
  },
  PA: {
    check_in: 'ਚੈੱਕ-ਇਨ',
    manual_entry: 'ਦਸਤੀ ਦਾਖਲਾ',
    status_check: 'ਸਥਿਤੀ ਦੀ ਜਾਂਚ',
    token_lookup: 'ਟੋਕਨ ਖੋਜ',
    schedules: 'ਸਮਾਂ-ਸਾਰਣੀ',
    doctor_timings: 'ਡਾਕਟਰ ਦਾ ਸਮਾਂ',
    listening: 'ਸੁਣ ਰਿਹਾ ਹੈ... ਰੋਕਣ ਲਈ ਟੈਪ ਕਰੋ.',
    processing: 'ਕਾਰਵਾਈ ਹੋ ਰਹੀ ਹੈ',
    understood: 'ਸਮਝ ਗਿਆ',
    network_error: 'ਨੈੱਟਵਰਕ ਗਲਤੀ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ.',
    welcome: 'MediVERSE ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ',
    hospital_system: 'ਹਸਪਤਾਲ ਸਵੈ-ਸੇਵਾ ਸਿਸਟਮ',
    select_language: 'ਭਾਸ਼ਾ ਚੁਣੋ',
    choose_pref: 'ਜਾਰੀ ਰੱਖਣ ਲਈ ਆਪਣੀ ਪਸੰਦੀਦਾ ਭਾਸ਼ਾ ਚੁਣੋ.',
    continue_btn: 'ਜਾਰੀ ਰੱਖੋ',
    gesture_on: 'ਜੈਸਚਰ ਕੰਟਰੋਲ ਆਨ (ਕੋਈ ਸਕ੍ਰੀਨ ਟੱਚ ਨਹੀਂ)',
    gesture_off: 'ਜੈਸਚਰ ਚਾਲੂ ਕਰੋ',
    how_to_use: 'ਕਿਵੇਂ ਵਰਤਣਾ ਹੈ',
    step_1: 'ਕਦਮ 1: ਕੈਮਰੇ ਵੱਲ ਦੇਖੋ -- ਤੁਹਾਡਾ ਚਿਹਰਾ ਦਿਖਾਈ ਦੇਣਾ ਚਾਹੀਦਾ ਹੈ.',
    step_2: 'ਕਦਮ 2: ਇੱਕ ਉਂਗਲ ਉਠਾਓ = ਸਕ੍ਰੀਨ ਤੇ ਪੁਆਇੰਟਰ ਚਲਦਾ ਹੈ.',
    step_3: 'ਕਦਮ 3: ਚੁਟਕੀ ਭਰੋ (ਅੰਗੂਠਾ + ਇੰਡੈਕਸ ਉਂਗਲ) = ਕਲਿੱਕ ਕਰੋ.',
    face_req: 'ਸੁਰੱਖਿਆ ਲਈ ਚਿਹਰੇ ਦੀ ਪਛਾਣ ਜ਼ਰੂਰੀ ਹੈ.',
    no_touch: 'ਸਕ੍ਰੀਨ ਨੂੰ ਛੂਹਣ ਦੀ ਲੋੜ ਨਹੀਂ ਹੈ.',
    gesture_desc: 'ਜੈਸਚਰ ਮੋਡ ਤੁਹਾਡੇ ਕੈਮਰੇ ਦੀ ਵਰਤੋਂ ਕਰਦਾ ਹੈ। ਕੋਈ ਡਾਟਾ ਸੇਵ ਨਹੀਂ ਹੁੰਦਾ.',
    primary_lang: 'ਪ੍ਰਾਇਮਰੀ',
    jharkhand_lang: 'ਝਾਰਖੰਡ ਖੇਤਰੀ',
    other_indian: 'ਹੋਰ ਭਾਰਤੀ',
    foreign_lang: 'ਵਿਦੇਸ਼ੀ',
  },
  ES: {
    check_in: 'REGISTRARSE',
    manual_entry: 'Entrada Manual',
    status_check: 'ESTADO',
    token_lookup: 'Buscar Ficha',
    schedules: 'HORARIOS',
    doctor_timings: 'Horarios del Doctor',
    listening: 'Escuchando... Toca para detener.',
    processing: 'Procesando',
    understood: 'Entendido',
    network_error: 'Error de red. Inténtalo de nuevo.',
    welcome: 'Bienvenido a MediVERSE',
    hospital_system: 'Sistema de Autoservicio del Hospital',
    select_language: 'SELECCIONAR IDIOMA',
    choose_pref: 'Elija su idioma preferido para continuar.',
    continue_btn: 'CONTINUAR',
    gesture_on: 'Control de Gestos ACTIVADO',
    gesture_off: 'Habilitar Gestos',
    how_to_use: 'CÓMO USAR',
    step_1: 'Paso 1: Mire a la cámara -- su rostro debe ser visible.',
    step_2: 'Paso 2: Levante un dedo = El puntero se mueve.',
    step_3: 'Paso 3: Pellizcar (pulgar + índice) = Clic.',
    face_req: 'Se requiere detección facial por seguridad.',
    no_touch: 'No es necesario tocar la pantalla.',
    gesture_desc: 'El modo de gestos usa su cámara. No se guardan datos.',
    primary_lang: 'PRINCIPAL',
    jharkhand_lang: 'REGIONAL',
    other_indian: 'OTROS IDIOMAS',
    foreign_lang: 'EXTRANJERO',
  },
  FR: {
    check_in: 'S\'ENREGISTRER',
    manual_entry: 'Saisie Manuelle',
    status_check: 'STATUT',
    token_lookup: 'Recherche de Jeton',
    schedules: 'HORAIRES',
    doctor_timings: 'Horaires du Docteur',
    listening: 'Écoute... Appuyez pour arrêter.',
    processing: 'Traitement',
    understood: 'Compris',
    network_error: 'Erreur réseau. Veuillez réessayer.',
    welcome: 'Bienvenue chez MediVERSE',
    hospital_system: 'Système en Libre-Service de l\'Hôpital',
    select_language: 'CHOISIR LA LANGUE',
    choose_pref: 'Choisissez votre langue préférée pour continuer.',
    continue_btn: 'CONTINUER',
    gesture_on: 'Contrôle Gestuel ACTIVÉ',
    gesture_off: 'Activer les Gestes',
    how_to_use: 'COMMENT UTILISER',
    step_1: 'Étape 1: Regardez la caméra -- votre visage doit être visible.',
    step_2: 'Étape 2: Levez un doigt = Le pointeur bouge.',
    step_3: 'Étape 3: Pincer (pouce + index) = Clic.',
    face_req: 'La détection faciale est requise pour la sécurité.',
    no_touch: 'Pas besoin de toucher l\'écran.',
    gesture_desc: 'Le mode gestuel utilise votre caméra. Aucune donnée n\'est stockée.',
    primary_lang: 'PRINCIPAL',
    jharkhand_lang: 'RÉGIONAL',
    other_indian: 'AUTRES LANGUES',
    foreign_lang: 'ÉTRANGER',
  },
  DE: {
    check_in: 'EINCHECKEN',
    manual_entry: 'Manuelle Eingabe',
    status_check: 'STATUS PRÜFEN',
    token_lookup: 'Token-Suche',
    schedules: 'ZEITPLÄNE',
    doctor_timings: 'Arztzeiten',
    listening: 'Zuhören... Tippen zum Stoppen.',
    processing: 'Verarbeitung',
    understood: 'Verstanden',
    network_error: 'Netzwerkfehler. Bitte versuchen Sie es erneut.',
    welcome: 'Willkommen bei MediVERSE',
    hospital_system: 'Krankenhaus-Selbstbedienungssystem',
    select_language: 'SPRACHE WÄHLEN',
    choose_pref: 'Wählen Sie Ihre bevorzugte Sprache, um fortzufahren.',
    continue_btn: 'WEITER',
    gesture_on: 'Gestensteuerung EIN',
    gesture_off: 'Gesten Aktivieren',
    how_to_use: 'ANLEITUNG',
    step_1: 'Schritt 1: Schauen Sie in die Kamera.',
    step_2: 'Schritt 2: Heben Sie einen Finger = Zeiger bewegt sich.',
    step_3: 'Schritt 3: Kneifen (Daumen + Zeigefinger) = Klicken.',
    face_req: 'Gesichtserkennung aus Sicherheitsgründen erforderlich.',
    no_touch: 'Kein Bildschirm-Touch nötig.',
    gesture_desc: 'Der Gestenmodus nutzt Ihre Kamera. Es werden keine Daten gespeichert.',
    primary_lang: 'PRIMÄR',
    jharkhand_lang: 'REGIONAL',
    other_indian: 'ANDERE SPRACHEN',
    foreign_lang: 'AUSLÄNDISCH',
  },
  ZH: {
    check_in: '报到',
    manual_entry: '手动输入',
    status_check: '状态检查',
    token_lookup: '令牌查询',
    schedules: '时间表',
    doctor_timings: '医生时间',
    listening: '听... 点击停止。',
    processing: '处理中',
    understood: '明白',
    network_error: '网络错误。请重试。',
    welcome: '欢迎来到 MediVERSE',
    hospital_system: '医院自助服务系统',
    select_language: '选择语言',
    choose_pref: '选择您喜欢的语言以继续。',
    continue_btn: '继续',
    gesture_on: '手势控制开启',
    gesture_off: '启用手势控制',
    how_to_use: '使用说明',
    step_1: '第1步：面向摄像头 -- 必须看到您的脸。',
    step_2: '第2步：举起一根手指 = 移动光标。',
    step_3: '第3步：捏合（拇指+食指）= 点击。',
    face_req: '为了安全起见，需要进行面部识别。',
    no_touch: '无需触摸屏幕。',
    gesture_desc: '手势模式使用您的摄像头。不存储任何数据。',
    primary_lang: '主要',
    jharkhand_lang: '地方语言',
    other_indian: '其他语言',
    foreign_lang: '外语',
  },
  AR: {
    check_in: 'تسجيل الدخول',
    manual_entry: 'إدخال يدوي',
    status_check: 'التحقق من الحالة',
    token_lookup: 'البحث عن رمز',
    schedules: 'الجداول',
    doctor_timings: 'أوقات الطبيب',
    listening: 'يستمع... انقر للإيقاف.',
    processing: 'معالجة',
    understood: 'مفهوم',
    network_error: 'خطأ في الشبكة. حاول مرة أخرى.',
    welcome: 'مرحبًا بك في MediVERSE',
    hospital_system: 'نظام الخدمة الذاتية بالمستشفى',
    select_language: 'اختر اللغة',
    choose_pref: 'اختر لغتك المفضلة للمتابعة.',
    continue_btn: 'متابعة',
    gesture_on: 'تشغيل التحكم بالإيماءات',
    gesture_off: 'تمكين الإيماءات',
    how_to_use: 'كيفية الاستخدام',
    step_1: 'الخطوة 1: انظر إلى الكاميرا -- يجب أن يكون وجهك مرئيًا.',
    step_2: 'الخطوة 2: ارفع إصبعًا واحدًا = يتحرك المؤشر.',
    step_3: 'الخطوة 3: قرص (الإبهام + السبابة) = نقر.',
    face_req: 'مطلوب التعرف على الوجه للأمان.',
    no_touch: 'لا داعي للمس الشاشة.',
    gesture_desc: 'يستخدم وضع الإيماءات الكاميرا الخاصة بك. لا يتم حفظ أي بيانات.',
    primary_lang: 'رئيسي',
    jharkhand_lang: 'إقليمي',
    other_indian: 'لغات أخرى',
    foreign_lang: 'أجنبي',
  },
  RU: {
    check_in: 'РЕГИСТРАЦИЯ',
    manual_entry: 'Ручной ввод',
    status_check: 'ПРОВЕРКА СТАТУСА',
    token_lookup: 'Поиск токена',
    schedules: 'РАСПИСАНИЕ',
    doctor_timings: 'Время врача',
    listening: 'Слушаю... Нажмите, чтобы остановить.',
    processing: 'Обработка',
    understood: 'Понятно',
    network_error: 'Ошибка сети. Пожалуйста, попробуйте еще раз.',
    welcome: 'Добро пожаловать в MediVERSE',
    hospital_system: 'Система самообслуживания больницы',
    select_language: 'ВЫБЕРИТЕ ЯЗЫК',
    choose_pref: 'Выберите предпочитаемый язык для продолжения.',
    continue_btn: 'ПРОДОЛЖИТЬ',
    gesture_on: 'Управление жестами ВКЛ',
    gesture_off: 'Включить жесты',
    how_to_use: 'КАК ИСПОЛЬЗОВАТЬ',
    step_1: 'Шаг 1: Смотрите в камеру -- ваше лицо должно быть видно.',
    step_2: 'Шаг 2: Поднимите один палец = указатель перемещается.',
    step_3: 'Шаг 3: Щипок (большой + указательный) = клик.',
    face_req: 'Для безопасности требуется распознавание лиц.',
    no_touch: 'Прикасаться к экрану не нужно.',
    gesture_desc: 'Режим жестов использует вашу камеру. Данные не сохраняются.',
    primary_lang: 'ОСНОВНОЙ',
    jharkhand_lang: 'РЕГИОНАЛЬНЫЙ',
    other_indian: 'ДРУГИЕ ЯЗЫКИ',
    foreign_lang: 'ИНОСТРАННЫЙ',
  },
  JA: {
    check_in: 'チェックイン',
    manual_entry: '手動入力',
    status_check: 'ステータス確認',
    token_lookup: 'トークン検索',
    schedules: 'スケジュール',
    doctor_timings: '医師の時間',
    listening: '聞いています... 停止するにはタップ。',
    processing: '処理中',
    understood: '了解しました',
    network_error: 'ネットワークエラー。もう一度お試しください。',
    welcome: 'MediVERSEへようこそ',
    hospital_system: '病院セルフサービスシステム',
    select_language: '言語を選択',
    choose_pref: '続行するには、ご希望の言語を選択してください。',
    continue_btn: '続行',
    gesture_on: 'ジェスチャー操作ON',
    gesture_off: 'ジェスチャーを有効にする',
    how_to_use: '使い方',
    step_1: 'ステップ1：カメラを見てください -- 顔が見える必要があります。',
    step_2: 'ステップ2：指を1本上げる = ポインタが移動します。',
    step_3: 'ステップ3：ピンチ（親指＋人差し指）= クリック。',
    face_req: 'セキュリティのため顔認識が必要です。',
    no_touch: '画面に触れる必要はありません。',
    gesture_desc: 'ジェスチャーモードはカメラを使用します。データは保存されません。',
    primary_lang: '主要',
    jharkhand_lang: '地域言語',
    other_indian: 'その他の言語',
    foreign_lang: '外国語',
  },
};

interface LanguageContextProps {
  lang: Language;
  setLang: (lang: Language) => void;
  t: (key: string, forceLang?: Language) => string;
}

const LanguageContext = createContext<LanguageContextProps>({
  lang: 'EN',
  setLang: () => {},
  t: (key: string) => key,
});

export const LanguageProvider = ({ children }: { children: React.ReactNode }) => {
  const [lang, setLangState] = useState<Language>('EN');

  useEffect(() => {
    const saved = localStorage.getItem('mediverse_lang') as Language;
    if (saved && TRANSLATIONS[saved]) {
      setLangState(saved);
    }
  }, []);

  const setLang = (newLang: Language) => {
    setLangState(newLang);
    localStorage.setItem('mediverse_lang', newLang);
  };

  const t = (key: string, forceLang?: Language) => {
    return TRANSLATIONS[forceLang || lang]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
